import test from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { flightKey,comparisonGate,parseAirportSheets,readAirportWorkbook,compareGates,clipOccupancy,occupancyConflicts,occupancyConflictIds,occupancyFlights,occupancyRowGate,formatOccupancyDuration,sortGates,applyOccupancyPickups,type AirportPlan } from '../lib/gates.ts';
import { analyze,makeMoves,longMoves,exportCSV,parseCSV,moveErrors,type Report } from '../lib/tows.ts';
import { sampleCSV } from './fixtures/sample.ts';
const header=['Arr Flight','Arr Time','ETA',null,'Arr Sector','Dep Flight','Dep Time','ETD','Dep Sector','Gate'];
const report=analyze(sampleCSV);
const mini:Report={...report,turns:[{...report.turns.find(t=>t.arrFlight==='QK 8672'&&t.from==='89')!,id:'t'}]};
const make=(rows:unknown[][])=>parseAirportSheets([{name:'Airport',rows:[['2026-09-05 Montréal-Trudeau'],header,...rows]}],'gates.xlsx');
const row=(gate='88')=>['ACA8672',new Date('2026-09-05T18:22:00Z'),null,null,'T','ACA8851',new Date('2026-09-05T19:30:00Z'),null,'T',gate];
test('carrier aliases are scoped; numeric gate suffixes are equivalent',()=>{assert.equal(flightKey('QK 08672'),flightKey('ACA8672'));assert.equal(flightKey('JZA8672'),flightKey('AC8672'));assert.notEqual(flightKey('AA8672'),flightKey('AC8672'));assert.equal(comparisonGate('2A'),'02');assert.equal(comparisonGate('A2'),'02');assert.equal(comparisonGate('C74'),'74');assert.equal(comparisonGate('79A'),'79');assert.equal(comparisonGate('21A'),'21');assert.equal(comparisonGate('A21'),'21');assert.equal(comparisonGate('021B'),'21');assert.equal(comparisonGate('S4B'),'S4B');assert.equal(comparisonGate('BSE'),'BSE');});
test('same flight number and day matches arrival/departure independently',()=>{const checks=compareGates(mini,make([row()]),[]);assert.equal(checks.length,2);assert.ok(checks.every(c=>c.status==='mismatch'));assert.deepEqual(checks.map(c=>c.direction),['arrival','departure']);assert.ok(checks.every(c=>c.airportGate==='88'));});
test('dates prevent matching another day; ETA midnight dates are considered',()=>{const r=row();r[1]=new Date('2026-09-04T23:00:00Z');const p=make([r]);assert.equal(compareGates(mini,p,[])[0].status,'unmatched');p.assignments[0].dates.push('2026-09-05');assert.equal(compareGates(mini,p,[])[0].status,'mismatch');});
test('split TOW rows pair by direction rather than workbook row',()=>{const a=row('89');a[5]='';a[6]='TOW';const d=row('75');d[0]='';d[1]='TOW';const c=compareGates(mini,make([a,d]),[]);assert.equal(c[0].status,'match');assert.equal(c[1].status,'mismatch');assert.equal(c[1].airportGate,'75');});
test('duplicates with same gate match; conflicting or missing gates need verification',()=>{assert.equal(compareGates(mini,make([row('89'),row('89')]),[])[0].status,'match');assert.equal(compareGates(mini,make([row('89'),row('88')]),[])[0].status,'ambiguous');assert.equal(compareGates(mini,make([row('')]),[])[0].status,'missing');});
test('active tow movements and potential tows appear in review; ordinary turns do not',()=>{const p=make([row()]);assert.equal(compareGates(mini,p,[])[0].tow,false);const gateTurn={...mini,turns:mini.turns.map(t=>({...t,kind:'gate' as const}))};assert.equal(compareGates(gateTurn,p,[])[0].tow,true);const bse={...mini,turns:mini.turns.map(t=>({...t,kind:'bse-in' as const}))};const c=compareGates(bse,p,makeMoves(bse));assert.equal(c[0].tow,true);assert.equal(c[1].tow,false);});
test('unsupported workbook rejected, missing dates warned, no number-only matching',()=>{assert.throws(()=>parseAirportSheets([{name:'Other',rows:[['hello']]}],'x.xlsx'));const r=row();r[1]='TOW';const p=make([r]);assert.equal(p.assignments.length,1);assert.ok(p.warnings.length);assert.equal(flightKey('8672'),'');});
test('supplied airport workbook loads and compares against supplied CSV',async()=>{const buffer=await readFile(new URL('./fixtures/airport-planning.xlsx',import.meta.url));const plan=await readAirportWorkbook(buffer.buffer.slice(buffer.byteOffset,buffer.byteOffset+buffer.byteLength),'airport.xlsx');assert.equal(plan.date,'2026-09-05');assert.ok(plan.assignments.length>200);assert.ok(plan.assignments.some(a=>a.key==='AC8614'&&a.direction==='departure'&&a.gate==='75'));const checks=compareGates(report,plan,makeMoves(report));assert.ok(checks.some(c=>c.flight==='QK 8672'&&c.date==='2026-09-05'&&c.direction==='arrival'&&c.status==='mismatch'&&c.airportGate==='88'));assert.ok(checks.some(c=>c.flight==='QK 7884'&&c.status==='match'));console.log(JSON.stringify({assignments:plan.assignments.length,mismatches:checks.filter(c=>c.status==='mismatch').length,matched:checks.filter(c=>c.status==='match').length,unverified:checks.filter(c=>!['match','mismatch'].includes(c.status)).length,towChecks:checks.filter(c=>c.tow&&c.status!=='match').length}));});

test('letter variants do not create mismatches or ambiguous duplicates',()=>{const csv={...mini,turns:mini.turns.map(t=>({...t,from:'21',to:'21'}))};const checks=compareGates(csv,make([row('21A'),row('21B'),row('21')]),[]);assert.ok(checks.every(c=>c.status==='match'));const actual=compareGates(csv,make([row('22A')]),[]);assert.ok(actual.every(c=>c.status==='mismatch'));});
test('occupancy rows merge only the listed lettered stands',()=>{
 assert.equal(occupancyRowGate('2A'),'02');
 assert.equal(occupancyRowGate('02'),'02');
 assert.equal(occupancyRowGate('5A'),'05');
 assert.equal(occupancyRowGate('11B'),'11');
 assert.equal(occupancyRowGate('77B'),'77');
 assert.equal(occupancyRowGate('79A'),'79');
 assert.equal(occupancyRowGate('84A'),'84');
 assert.equal(occupancyRowGate('19B'),'19B');
 assert.equal(occupancyRowGate('19'),'19');
 assert.equal(occupancyRowGate('21A'),'21A');
});
test('workbook rows become gate occupancies with airline, flights and duration',()=>{
 const p=make([row()]);
 assert.equal(p.occupancies.length,1);
 assert.equal(p.occupancies[0].gate,'88');
 assert.equal(p.occupancies[0].airline,'AC');
 assert.equal(occupancyFlights(p.occupancies[0]),'ACA8672 / ACA8851');
 assert.equal(formatOccupancyDuration(Date.parse('2026-09-05T19:30:00Z')-Date.parse('2026-09-05T18:22:00Z')),'1h 8m');
 const span=clipOccupancy(p.occupancies[0],'2026-09-05');
 assert.ok(span&&!span.estimated);
 assert.deepEqual(sortGates(['S4B','79A','02','10']),['02','10','79A','S4B']);
});
test('overnight and tow rows still plot on the operating day',()=>{
 const overnight=['', 'O/N', null, null, 'D', 'ACA7738', new Date('2026-09-05T07:30:00Z'), null, 'D', '23'];
 const towIn=['', 'TOW', null, null, 'D', 'ACA7951', new Date('2026-09-05T06:30:00Z'), null, 'D', '2'];
 const towOut=['ACA316', new Date('2026-09-05T06:15:00Z'), null, null, 'D', '', 'TOW', null, 'D', '47'];
 const p=make([overnight,towIn,towOut]);
 assert.equal(p.occupancies.length,3);
 assert.equal(p.occupancies[0].overnight,true);
 assert.equal(p.occupancies[1].towedIn,true);
 assert.equal(p.occupancies[2].towedOut,true);
 const night=clipOccupancy(p.occupancies[0],'2026-09-05');
 assert.ok(night&&night.start===Date.parse('2026-09-05T00:00:00Z')&&!night.estimated);
 assert.equal(night.block,'overnight');
 assert.equal(night.kind,'departure');
 const inbound=clipOccupancy(p.occupancies[1],'2026-09-05');
 assert.ok(inbound&&inbound.estimated);
 assert.equal(inbound.block,'tow-in');
 assert.equal(inbound.kind,'departure');
 assert.equal(inbound.end-inbound.start,60*60000);
 const outbound=clipOccupancy(p.occupancies[2],'2026-09-05');
 assert.ok(outbound&&outbound.estimated);
 assert.equal(outbound.block,'tow-out');
 assert.equal(outbound.kind,'arrival');
 assert.equal(outbound.end-outbound.start,30*60000);
});
test('previous-day arrivals stay overnight only before 09:00',()=>{
 const morning=['ACA100', new Date('2026-09-04T22:10:00Z'), null, null, 'D', 'ACA101', new Date('2026-09-05T07:55:00Z'), null, 'D', '12'];
 const late=['ACA200', new Date('2026-09-04T21:44:00Z'), null, null, 'D', 'ACA201', new Date('2026-09-05T18:30:00Z'), null, 'D', '14'];
 const overnightLate=['', 'O/N', null, null, 'D', 'ACA300', new Date('2026-09-05T10:40:00Z'), null, 'D', '16'];
 const nine=['ACA400', new Date('2026-09-04T23:00:00Z'), null, null, 'D', 'ACA401', new Date('2026-09-05T09:00:00Z'), null, 'D', '17'];
 const prevTowOut=['ACA500', new Date('2026-09-04T22:00:00Z'), null, null, 'D', '', 'TOW', null, 'D', '18'];
 const p=make([morning,late,overnightLate,nine,prevTowOut]);
 const stay=clipOccupancy(p.occupancies[0],'2026-09-05');
 assert.ok(stay&&!stay.estimated);
 assert.equal(stay.block,'overnight');
 assert.equal(stay.kind,'turn');
 assert.equal(stay.start,Date.parse('2026-09-05T00:00:00Z'));
 assert.equal(stay.end,Date.parse('2026-09-05T07:55:00Z'));
 const tow=clipOccupancy(p.occupancies[1],'2026-09-05');
 assert.ok(tow&&tow.estimated);
 assert.equal(tow.block,'tow-in');
 assert.equal(tow.kind,'departure');
 assert.equal(tow.end-tow.start,60*60000);
 assert.equal(tow.end,Date.parse('2026-09-05T18:30:00Z'));
 const onLate=clipOccupancy(p.occupancies[2],'2026-09-05');
 assert.ok(onLate&&onLate.estimated);
 assert.equal(onLate.block,'tow-in');
 assert.equal(onLate.end-onLate.start,60*60000);
 const atNine=clipOccupancy(p.occupancies[3],'2026-09-05');
 assert.ok(atNine&&atNine.estimated);
 assert.equal(atNine.block,'tow-in');
 assert.equal(clipOccupancy(p.occupancies[4],'2026-09-05'),null);
 assert.equal(formatOccupancyDuration(60*60000),'1h');
});
test('same-gate overlaps are flagged only when both times are known',()=>{
 const a=row('81');
 const b=['AAL4550', new Date('2026-09-05T19:00:00Z'), null, null, 'T', 'AAL4550', new Date('2026-09-05T20:00:00Z'), null, 'T', '81'];
 const overlap=occupancyConflicts(make([a,b]).occupancies,'2026-09-05');
 assert.equal(overlap.size,2);
 const clear=occupancyConflicts(make([a,['AAL4550', new Date('2026-09-05T20:00:00Z'), null, null, 'T', 'AAL4550', new Date('2026-09-05T21:00:00Z'), null, 'T', '81']]).occupancies,'2026-09-05');
 assert.equal(clear.size,0);
});
test('supplied airport workbook builds a full gate occupancy plan',async()=>{
 const buffer=await readFile(new URL('./fixtures/airport-planning.xlsx',import.meta.url));
 const plan=await readAirportWorkbook(buffer.buffer.slice(buffer.byteOffset,buffer.byteOffset+buffer.byteLength),'airport.xlsx');
 assert.ok(plan.occupancies.length>100);
 assert.ok(plan.occupancies.some(o=>o.arrFlight==='AAL5100'&&o.depFlight==='AAL5102'&&(o.gate==='83'||o.gate==='79A')));
 assert.ok(plan.occupancies.some(o=>o.gate==='S4B'||o.gate==='S1A'||o.gate==='W3'));
 assert.ok(plan.occupancies.some(o=>o.overnight));
 assert.ok(plan.occupancies.some(o=>o.towedIn||o.towedOut));
});
const turnHeader='Incoming,,,,,,,,Outgoing,,,,,\nOrigin,TOD,TOA,PAX,Flight,"Terminal\n/ Gate",Tail,"Turn Time\n(HH:MM)","Terminal\n/ Gate",Flight,PAX,TOD,TOA,Destination\n';
function turnCsv(row:string){return turnHeader+row+`\n"Report Parameters (in Detail) :\nReport Period: 05Sep26 00:00 - 05Sep26 23:59 LT\nStation: YUL"`;}
const trow=(arr:string,dep:string,from:string,to:string,dur:string)=>`YTZ,0700/05 S,${arr},,QK 1,${from},431,${dur},${to},QK 2,,${dep},,YTZ`;
test('departure tow pickup is 5 min before the occupying aircraft frees the gate',()=>{
 const r=analyze(turnCsv(trow('2200/04 S','0700/05 S','/ 80','/ 80','09:00')));
 const ms=makeMoves(r);
 assert.equal(ms[0].kind,'bse-out');
 assert.equal(ms[0].pickup,'06:00');
 const plan=make([['AAL9', new Date('2026-09-05T05:00:00Z'), null, null, 'T', 'AAL10', new Date('2026-09-05T06:40:00Z'), null, 'T', '80']]);
 const timed=applyOccupancyPickups(ms,r,plan.occupancies);
 assert.equal(timed[0].pickup,'06:30');
 assert.equal(timed[0].gateOpen,'06:35');
 assert.ok(timed[0].warnings.some(w=>/gate 80 opens/i.test(w)));
 const csv=exportCSV(r,timed,true),rows=parseCSV(csv);
 assert.equal(rows[1][6],'TIME GATE OPENS AT');
 assert.equal(rows[2][6],'0635');
 assert.equal(applyOccupancyPickups([{...ms[0],reviewed:true}],r,plan.occupancies)[0].pickup,'06:00');
});
test('other-company arrival tow-off uses 1h 30m before departure or 30 min after that arrival',()=>{
 const r=analyze(turnCsv(trow('0800/05 S','1200/05 S','/ 02','/ 80','04:00')));
 assert.equal(r.turns[0].kind,'gate');
 const ms=makeMoves(r);
 assert.equal(ms[0].pickup,'08:00');
 const late=make([['POE135', new Date('2026-09-05T11:00:00Z'), null, null, 'D', '', 'TOW', null, 'D', '80']]);
 const after=applyOccupancyPickups(ms,r,late.occupancies)[0];
 assert.equal(after.pickup,'11:30');
 assert.equal(after.gateOpen,'11:30');
 const early=make([['POE135', new Date('2026-09-05T09:00:00Z'), null, null, 'D', '', 'TOW', null, 'D', '80']]);
 const preferred=applyOccupancyPickups(ms,r,early.occupancies)[0];
 assert.equal(preferred.pickup,'10:30');
 assert.equal(preferred.gateOpen,'09:30');
});
test('holding return tows follow dest-gate occupancy; outbound arrival tows do not',()=>{
 const r=analyze(turnCsv(trow('0800/05 S','1400/05 S','/ 02','/ 02','06:00')));
 const pair=longMoves(r.turns[0],'BSE');
 const plan=make([['UAL1', new Date('2026-09-05T12:00:00Z'), null, null, 'T', 'UAL2', new Date('2026-09-05T13:20:00Z'), null, 'T', '02']]);
 const timed=applyOccupancyPickups(pair,r,plan.occupancies);
 assert.equal(timed[0].pickup,'08:00');
 assert.equal(timed[1].pickup,'13:10');
 assert.equal(timed[1].gateOpen,'13:15');
});
test('occupant departing after planned departure is warned instead of silently clamped',()=>{
 const r=analyze(turnCsv(trow('2200/04 S','1200/05 S','/ 80','/ 80','14:00')));
 const ms=makeMoves(r);
 assert.equal(ms[0].kind,'bse-out');
 const plan=make([['AAL9', new Date('2026-09-05T11:00:00Z'), null, null, 'T', 'AAL10', new Date('2026-09-05T12:30:00Z'), null, 'T', '80']]);
 const timed=applyOccupancyPickups(ms,r,plan.occupancies)[0];
 assert.equal(timed.pickup,'12:20');
 assert.equal(timed.gateOpen,'12:25');
 assert.ok(timed.warnings.some(w=>/cannot support this departure/i.test(w)));
 assert.ok(moveErrors(timed,r.date).some(e=>/before departure/i.test(e)));
});
test('overlap membership ignores airline filters and different gates',()=>{
 const a=row('81');
 const b=['AAL4550', new Date('2026-09-05T19:00:00Z'), null, null, 'T', 'AAL4550', new Date('2026-09-05T20:00:00Z'), null, 'T', '81'];
 const otherGate=['UAL1', new Date('2026-09-05T19:00:00Z'), null, null, 'T', 'UAL2', new Date('2026-09-05T20:00:00Z'), null, 'T', '82'];
 const plan=make([a,b,otherGate]);
 const all=occupancyConflictIds(plan.occupancies,'2026-09-05');
 assert.equal(all.size,2);
 assert.ok([...all].every(id=>id.startsWith('Airport:')));
 const acOnly=plan.occupancies.filter(o=>o.airline==='AC');
 assert.equal(occupancyConflicts(acOnly,'2026-09-05').size,0);
 assert.ok(acOnly.some(o=>all.has(o.id)));
 assert.ok(!all.has(plan.occupancies.find(o=>o.gate==='82')!.id));
});
