'use client';
import { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { flushSync } from 'react-dom';
import { Plane, Upload, ArrowRight, FileSpreadsheet, CheckCircle2, MoveRight, Warehouse, Clock3, Download, Printer, SlidersHorizontal, Info, Pencil, Search, AlertTriangle, Check, X } from 'lucide-react';
import { Table, TableHeader, TableHead, TableRow, TableBody, TableCell } from '@/components/ui/table';
import { Tabs, TabsList, TabsTrigger, TabsContent } from '@/components/ui/tabs';
import { Checkbox } from '@/components/ui/checkbox';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Sheet, SheetContent, SheetHeader, SheetTitle, SheetDescription } from '@/components/ui/sheet';
import { sampleCSV } from '@/lib/sample';
import { analyze, makeMoves, longMoves, moveErrors, timeLabel, sheetHeaders, sheetValues, exportCSV, planIssues, gate, type Report, type Turn, type Move } from '@/lib/tows';
const initialReport=analyze(sampleCSV);
const kindLabel={gate:'Gate change','bse-in':'To BSE','bse-out':'From BSE',long:'Long stay',none:'No tow',incomplete:'Missing data'};
const shortFlight=(s:string)=>s.replace(/^QK\s*/,'');
const formatDate=(date:string)=>new Date(date+'T12:00:00Z').toLocaleDateString('en-GB',{day:'2-digit',month:'long',year:'numeric',timeZone:'UTC'});
type Registry={registerTool:(tool:{name:string;title:string;description:string;inputSchema:object;annotations:object;execute:(v:unknown)=>unknown},options:{signal:AbortSignal})=>void|Promise<void>};

export default function Home(){
 const [report,setReport]=useState<Report>(initialReport),[moves,setMoves]=useState<Move[]>(()=>makeMoves(initialReport));
 const [fileName,setFileName]=useState('turn-view-YUL-1788635325.csv'),[sample,setSample]=useState(true);
 const [tab,setTab]=useState('moves'),[search,setSearch]=useState(''),[error,setError]=useState(''),[notice,setNotice]=useState(''),[loading,setLoading]=useState(false),[dragging,setDragging]=useState(false);
 const [dateOverride,setDateOverride]=useState(''),[decisions,setDecisions]=useState<Record<string,string>>({}),[holding,setHolding]=useState<Record<string,string>>({});
 const [editing,setEditing]=useState<Move|null>(null),[editError,setEditError]=useState('');
 const fileInput=useRef<HTMLInputElement>(null);
 const selected=useMemo(()=>moves.filter(m=>m.included).sort((a,b)=>(a.pickup||'99').localeCompare(b.pickup||'99')||a.fin.localeCompare(b.fin)),[moves]);
 const longTurns=report.turns.filter(t=>t.kind==='long');
 const pendingLong=longTurns.filter(t=>!decisions[t.id]);
 const unresolved=moves.filter(m=>m.kind==='incomplete'&&!m.reviewed);
 const unreviewed=selected.filter(m=>!m.reviewed||moveErrors(m,report.date).length>0);
 const issues=planIssues(moves);
 const draft=issues.length>0||unreviewed.length>0||pendingLong.length>0||unresolved.length>0||report.warnings.length>0;
 const filtered=moves.filter(m=>`${m.fin} ${m.arrFlight} ${m.depFlight} ${m.from} ${m.to}`.toLowerCase().includes(search.toLowerCase())).sort((a,b)=>(a.pickup||'99').localeCompare(b.pickup||'99')||a.fin.localeCompare(b.fin));
 const importText=useCallback((text:string,name:string,date?:string)=>{
  const result=analyze(text,date);setReport(result);setMoves(makeMoves(result));setFileName(name);setSample(false);setDecisions({});setHolding({});setEditing(null);setSearch('');setTab('moves');setError('');setNotice(`${result.turns.length} aircraft turns analyzed. Review the proposed moves before issuing the sheet.`);return result;
 },[]);
 async function upload(file:File){setError('');setLoading(true);try{if(file.size>5*1024*1024)throw Error('Please use a CSV smaller than 5 MB.');if(!/\.csv$/i.test(file.name))throw Error('Please upload a .csv flight schedule.');importText(await file.text(),file.name,dateOverride||undefined);}catch(e){setError(e instanceof Error?e.message:'Unable to read this file.');}finally{setLoading(false);if(fileInput.current)fileInput.current.value='';}}
 const stateRef=useRef({report,moves,importText});stateRef.current={report,moves,importText};
 useEffect(()=>{
  const registry=(document as Document&{modelContext?:Registry}).modelContext;if(!registry?.registerTool)return;const lifecycle=new AbortController();
  const tools=[{name:'analyze_flight_csv',title:'Analyze flight CSV',description:'Replace the current working schedule with a turn-view CSV and display suggested tows. Current edits are replaced.',inputSchema:{type:'object',properties:{csv:{type:'string'},fileName:{type:'string'},operatingDate:{type:'string'}},required:['csv'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:true},execute:(input:unknown)=>{const v=input as Record<string,unknown>;if(!v||typeof v.csv!=='string'||v.csv.length>5*1024*1024||v.operatingDate!==undefined&&typeof v.operatingDate!=='string'||v.fileName!==undefined&&typeof v.fileName!=='string')throw Error('Provide CSV text and an optional operating date / filename.');let r:Report|undefined;flushSync(()=>{r=stateRef.current.importText(v.csv as string,typeof v.fileName==='string'?v.fileName:'Uploaded schedule.csv',v.operatingDate as string|undefined);});return {date:r!.date,turns:r!.turns.length,proposedMoves:makeMoves(r!).length,cancelled:r!.cancelled};}},{name:'read_tow_plan',title:'Read tow plan',description:'Read the current tow plan, review status and data issues.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute:()=>({date:stateRef.current.report.date,moves:stateRef.current.moves,warnings:stateRef.current.report.warnings})}];
  for(const tool of tools){try{void Promise.resolve(registry.registerTool(tool,{signal:lifecycle.signal})).catch(()=>{});}catch{/* Browser support is optional. */}}return()=>lifecycle.abort();
 },[]);
 function patch(id:string,values:Partial<Move>){setMoves(ms=>ms.map(m=>m.id===id?{...m,...values}:m));}
 function reviewMove(m:Move){const errors=moveErrors(m,report.date);if(errors.length){setEditing(m);setEditError(errors.join(' '));return;}patch(m.id,{reviewed:!m.reviewed});}
 function decideLong(t:Turn,tow:boolean){try{const added=tow?longMoves(t,holding[t.id]||''):[];setMoves(ms=>[...ms.filter(m=>m.turnId!==t.id),...added]);setDecisions(ds=>({...ds,[t.id]:tow?'tow':'stay'}));setError('');setNotice(tow?`FIN ${t.fin}: added a holding move and return move.`:`FIN ${t.fin}: marked to stay at gate ${t.from}.`);}catch(e){setError((e as Error).message);}}
 function saveEdit(e:React.FormEvent){e.preventDefault();if(!editing)return;const errors=moveErrors(editing,report.date);if(errors.length){setEditError(errors.join(' '));return;}patch(editing.id,{...editing,from:gate(editing.from),to:gate(editing.to),reviewed:true});setEditing(null);setEditError('');setNotice(`FIN ${editing.fin}: move saved and reviewed.`);}
 function download(){const data=exportCSV(report,selected,draft);const url=URL.createObjectURL(new Blob([data],{type:'text/csv;charset=utf-8;'}));const a=document.createElement('a');a.href=url;a.download=`tow-sheet-${report.station}-${report.date}${draft?'-DRAFT':''}.csv`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);setNotice(`${draft?'Draft':'Reviewed'} tow sheet downloaded.`);}
 function print(){flushSync(()=>setTab('sheet'));window.print();}
 const flightCell=(flight:string,time:number|null)=> <><span>{shortFlight(flight)||'—'}</span><small>{timeLabel(time,report.date)}</small></>;
 return <><header className="masthead no-print"><div className="brand"><span className="brand-icon"><Plane size={24}/></span>Jazz<span>Tow</span><span className="brand-divider"/><small>GROUND OPERATIONS</small></div><span className="station"><span className="live-dot"/>{report.station} · {report.station==='YUL'?'Montréal':'Tow operations'}</span></header>
 <main><div className="page-heading no-print"><div><div className="eyebrow">DAILY OPERATIONS</div><h1>Tow planner</h1><p>From flight plan to tow sheet.</p></div><div className="date-pill">{formatDate(report.date)}<small>LOCAL TIME</small></div></div>
 <section className={`upload-panel no-print ${dragging?'dragging':''}`} onDragOver={e=>{e.preventDefault();setDragging(true);}} onDragLeave={()=>setDragging(false)} onDrop={e=>{e.preventDefault();setDragging(false);if(e.dataTransfer.files[0])void upload(e.dataTransfer.files[0]);}} aria-label="Upload flight schedule">
 <div className="upload-icon"><FileSpreadsheet/></div><div className="file-description"><div className="file-title"><strong>{fileName}</strong>{sample&&<span className="sample-badge">ATTACHED SAMPLE</span>}</div><p>{report.turns.length} aircraft turns · {report.cancelled} cancelled entries skipped{report.duplicates>0?` · ${report.duplicates} duplicates skipped`:''}</p></div><Button className="button primary" onClick={()=>fileInput.current?.click()} disabled={loading}><Upload size={17}/>{loading?'Reading CSV…':'Upload CSV'}</Button><input ref={fileInput} hidden type="file" accept=".csv,text/csv" onChange={e=>{if(e.target.files?.[0])void upload(e.target.files[0]);}}/>
 </section><div className="upload-footnote no-print"><span>Drop a turn-view CSV above. Files are processed in your browser; edits last for this session.</span><details><summary>Set upload date</summary><label>Only needed if the report date is missing<Input type="date" value={dateOverride} onChange={e=>setDateOverride(e.target.value)}/></label></details></div>
 {error&&<div role="alert" className="message error no-print"><AlertTriangle size={18}/>{error}<button aria-label="Dismiss error" onClick={()=>setError('')}><X size={16}/></button></div>}
 {issues.map(issue=><div role="alert" key={issue} className="message error no-print"><AlertTriangle size={18}/>{issue}</div>)}
 {notice&&<div role="status" className="message notice no-print"><CheckCircle2 size={17}/>{notice}<button aria-label="Dismiss notice" onClick={()=>setNotice('')}><X size={16}/></button></div>}
 <div className="stats no-print">{[{Icon:MoveRight,n:report.turns.filter(t=>t.kind==='gate').length,label:'Gate changes'},{Icon:Warehouse,n:report.turns.filter(t=>t.kind.startsWith('bse')).length,label:'BSE moves'},{Icon:Clock3,n:pendingLong.length,label:'Long stays to review'},{Icon:CheckCircle2,n:report.turns.filter(t=>t.kind==='none').length,label:'No tow needed'}].map(({Icon,n,label})=><div className="stat" key={label}><Icon size={21}/><div><strong>{n.toString().padStart(2,'0')}</strong><span>{label}</span></div></div>)}</div>
 <Tabs value={tab} onValueChange={value=>setTab(String(value))} className="workspace-tabs"><div className="workspace-toolbar no-print"><TabsList variant="line"><TabsTrigger value="moves">Tow moves <span className="count">{moves.length}</span></TabsTrigger><TabsTrigger value="review">Review <span className="count amber">{pendingLong.length+unresolved.length+report.warnings.length}</span></TabsTrigger><TabsTrigger value="schedule">Flight schedule</TabsTrigger><TabsTrigger value="sheet">Tower’s sheet</TabsTrigger></TabsList><div className="actions"><Button className="button" variant="outline" onClick={download} disabled={!selected.length}><Download size={16}/>Export CSV</Button><Button className="button primary" onClick={print} disabled={!selected.length}><Printer size={16}/>Print sheet</Button></div></div>
 <TabsContent value="moves" className="no-print"><section className="panel"><div className="panel-heading"><div><h2>Suggested moves</h2><p className="section-subtitle">{selected.length} included on sheet · {selected.length-unreviewed.length} reviewed</p></div><div className="search-box"><Search size={16}/><Input aria-label="Search tow moves" placeholder="Find aircraft, flight or gate" value={search} onChange={e=>setSearch(e.target.value)}/></div></div>
 {unreviewed.length>0&&<div className="inline-note"><Info size={16}/><span>Review each move before issuing. BSE locations are inferred from overnight turns.</span></div>}
 <Table><TableHeader><TableRow>{['USE','FIN #','ARRIVAL','TOW ROUTE','SKED PICKUP','DEPARTURE','REASON','REVIEW'].map(h=><TableHead key={h}>{h}</TableHead>)}</TableRow></TableHeader><TableBody>{filtered.map(m=>{const turn=report.turns.find(t=>t.id===m.turnId)!;const errs=moveErrors(m,report.date);return <TableRow key={m.id} className={!m.included?'excluded':''}><TableCell><Checkbox aria-label={`Include FIN ${m.fin} ${m.from} to ${m.to}`} checked={m.included} onCheckedChange={v=>patch(m.id,{included:!!v})}/></TableCell><TableCell className="fin">{m.fin||'—'}</TableCell><TableCell className="flight-cell">{flightCell(m.arrFlight,m.arrFlight?turn.arrival:null)}</TableCell><TableCell><div className="tow-route"><span className={m.from==='BSE'?'gate bse':'gate'}>{m.from||'?'}</span><ArrowRight size={15}/><span className={m.to==='BSE'?'gate bse':'gate'}>{m.to||'?'}</span></div></TableCell><TableCell><button className="pickup-edit" onClick={()=>{setEditing({...m});setEditError('');}} aria-label={`Edit FIN ${m.fin} pickup ${m.pickup||'unset'}`}>{m.pickup||'Set time'}<Pencil size={12}/></button></TableCell><TableCell className="flight-cell"><span>{shortFlight(m.depFlight)||'—'}</span><small>{m.depTime||'No departure today'}</small></TableCell><TableCell><span className={`reason-badge ${m.kind.startsWith('bse')?'blue':m.kind==='long'||m.kind==='incomplete'?'amber':''}`}>{kindLabel[m.kind]}</span>{(m.warnings.length>0||errs.length>0)&&<span className="row-warning" title={[...m.warnings,...errs].join(' ')}><AlertTriangle size={13}/> Check details</span>}</TableCell><TableCell><div className="row-actions"><button className={`review-button ${m.reviewed?'done':''}`} onClick={()=>reviewMove(m)} aria-label={`${m.reviewed?'Undo review':'Review'} FIN ${m.fin} ${m.from} to ${m.to}`}>{m.reviewed?<Check size={15}/>:<CheckCircle2 size={15}/>} {m.reviewed?'Reviewed':'Review'}</button><button className="icon-button" aria-label={`Edit FIN ${m.fin} ${m.from} to ${m.to}`} onClick={()=>{setEditing({...m});setEditError('');}}><Pencil size={15}/></button></div></TableCell></TableRow>})}</TableBody></Table>{!filtered.length&&<div className="empty-state">{moves.length?'No moves match your search.':'No tow moves identified for this schedule.'}</div>}
 <div className="panel-footer"><span>{selected.length} moves on the {draft?'draft':'reviewed'} sheet</span><span>All times local · HH:MM</span></div></section></TabsContent>
 <TabsContent value="review" className="no-print"><section className="panel review-panel"><div className="panel-heading"><div><h2>Review exceptions</h2><p className="section-subtitle">Choose whether long stays need a tow. Confirm unusual or incomplete data.</p></div></div>
 {report.warnings.map((w,i)=><div key={i} className="message error"><AlertTriangle size={18}/>{w} Correct the source and upload again.</div>)}
 {longTurns.map(t=><article className="review-card" key={t.id}><div className="review-card-top"><div><span className="eyebrow">SAME GATE · OVER 3 HOURS</span><h3>FIN {t.fin} <span>Gate {t.from}</span></h3></div><span className="reason-badge amber">{Math.floor((t.duration||0)/60)}h {(t.duration||0)%60}m on stand</span></div><p>{shortFlight(t.arrFlight)} arrives {timeLabel(t.arrival,report.date)} <ArrowRight size={14}/> {shortFlight(t.depFlight)} departs {timeLabel(t.departure,report.date)}</p>{decisions[t.id]?<div className="decision"><CheckCircle2 size={17}/>{decisions[t.id]==='stay'?'Confirmed: stay at gate.':'Two moves added: to holding stand and back to departure gate.'}<Button variant="ghost" onClick={()=>{setDecisions(ds=>{const d={...ds};delete d[t.id];return d;});setMoves(ms=>ms.filter(m=>m.turnId!==t.id));}}>Revisit</Button></div>:<div className="review-card-actions"><label>Holding stand<Input placeholder="e.g. BSE or stand #" value={holding[t.id]||''} onChange={e=>setHolding(h=>({...h,[t.id]:e.target.value}))}/></label><Button className="button" variant="outline" onClick={()=>decideLong(t,false)}>Keep at gate</Button><Button className="button primary" onClick={()=>decideLong(t,true)}>Add two tows <ArrowRight size={15}/></Button></div>}</article>)}
 {report.turns.filter(t=>t.warnings.length||t.kind==='incomplete').map(t=><article className="review-card" key={t.id}><h3>FIN {t.fin||'unassigned'} · {shortFlight(t.arrFlight)||shortFlight(t.depFlight)}</h3><p>{t.reason}</p>{t.warnings.map(w=><p className="warning-text" key={w}>{w}</p>)}{t.kind==='incomplete'&&<div className="review-card-actions"><Button className="button" onClick={()=>{const m=moves.find(m=>m.turnId===t.id);if(m){setEditing({...m,included:true});setEditError('');}}}>Complete move</Button><Button className="button" variant="outline" onClick={()=>patch(t.id,{reviewed:true,included:false})}>{moves.find(m=>m.id===t.id)?.reviewed?'Excluded after review':'Confirm no tow / exclude'}</Button></div>}</article>)}
 {!longTurns.length&&!report.turns.some(t=>t.warnings.length||t.kind==='incomplete')&&!report.warnings.length&&<div className="empty-state"><CheckCircle2/>No long stays or data exceptions to resolve.</div>}</section></TabsContent>
 <TabsContent value="schedule" className="no-print"><section className="panel"><div className="panel-heading"><h2>Flight schedule</h2><span className="muted">{report.turns.length} active turns · gate prefixes normalized</span></div><Table><TableHeader><TableRow>{['FIN #','ORIGIN','ARR FLIGHT','ARRIVAL (SOURCE)','ARR GATE','DEP GATE','DEP FLIGHT','DEPARTURE (SOURCE)','DESTINATION','RESULT'].map(h=><TableHead key={h}>{h}</TableHead>)}</TableRow></TableHeader><TableBody>{report.turns.map(t=><TableRow key={t.id}><TableCell className="fin">{t.fin||'—'}</TableCell><TableCell>{t.origin}</TableCell><TableCell>{shortFlight(t.arrFlight)||'—'}</TableCell><TableCell>{t.arrLabel||'—'}</TableCell><TableCell>{t.from||'—'}</TableCell><TableCell>{t.to||'—'}</TableCell><TableCell>{shortFlight(t.depFlight)||'—'}</TableCell><TableCell>{t.depLabel||'—'}</TableCell><TableCell>{t.destination}</TableCell><TableCell><span className={`reason-badge ${t.kind==='none'?'neutral':''}`}>{kindLabel[t.kind]}</span></TableCell></TableRow>)}</TableBody></Table><div className="panel-footer">Source times are preserved with their A / E / S indicators. The CSV may contain actual, estimated, and scheduled times.</div></section></TabsContent>
 <TabsContent value="sheet" className="sheet-tab"><section className="paper"><div className="paper-heading"><div className="paper-title">TOWER’S SHEET</div><div className="paper-brand">JazzTow <small>{report.station} · GROUND OPERATIONS</small></div><div className="paper-date"><span>DATE</span><strong>{formatDate(report.date).toUpperCase()}</strong></div></div><div className={`sheet-status ${draft?'draft':'ready'}`}>{draft?'DRAFT — REVIEW REQUIRED':'REVIEWED TOW SHEET'}<span>{draft?`${unreviewed.length} moves to review · ${pendingLong.length} long-stay decisions pending${unresolved.length?` · ${unresolved.length} incomplete turns`:''}${report.warnings.length?` · ${report.warnings.length} import issues`:''}${issues.length?` · ${issues.length} paired-tow issues`:''}`:`${selected.length} moves · All times local`}</span></div><Table className="tower-table"><TableHeader><TableRow><TableHead>#</TableHead>{sheetHeaders.map(h=><TableHead key={h}>{h}</TableHead>)}</TableRow></TableHeader><TableBody>{selected.map((m,i)=><TableRow key={m.id}><TableCell>{i+1}</TableCell>{sheetValues(m).map((v,j)=><TableCell key={j}>{v}</TableCell>)}</TableRow>)}{Array.from({length:Math.max(2,10-selected.length)},(_,i)=><TableRow key={`blank-${i}`}><TableCell>{selected.length+i+1}</TableCell>{sheetHeaders.map((_,j)=><TableCell key={j}>&nbsp;</TableCell>)}</TableRow>)}</TableBody></Table><div className="paper-footer">{report.station} · {report.date} · Local time<span>Prepared with JazzTow</span></div></section><p className="sheet-help no-print">Use the pencil beside a move to edit release, gate-open, actual pickup/drop, and tower fields. Print to paper or choose “Save as PDF”.</p></TabsContent></Tabs>
 <details className="rules no-print"><summary><SlidersHorizontal size={16}/> Tow rules <span>Arrival pickup at TOA · Departure pickup −60 min</span></summary><div className="rules-grid"><div><h3>Gate changes</h3><p>Different numbered gates produce a tow at arrival. Prefixes are ignored: C74 = 74 and A2 = 02.</p></div><div><h3>Overnight / BSE</h3><p>Arrival today and departure on a later day → BSE. Arrival before today and departure today → from BSE, 60 minutes before departure. Confirm the actual location.</p></div><div><h3>More than 3 hours</h3><p>Same-gate turns strictly over 3 hours require a decision. Adding a tow creates a holding move at arrival and a return 60 minutes before departure.</p></div><div><h3>Gate availability</h3><p>Gate-open times stay blank until provided. Pickup uses the time present in the CSV, which may be actual or estimated. Release and travel time are not included.</p></div></div></details>
 <footer className="app-footer no-print"><span>JazzTow · {report.station} operations</span><span>Review aircraft location and operational readiness before issuing.</span></footer></main>
 <Sheet open={!!editing} onOpenChange={open=>{if(!open)setEditing(null);}}><SheetContent className="edit-sheet"><SheetHeader><SheetTitle>Edit tow · FIN {editing?.fin||'unassigned'}</SheetTitle><SheetDescription>{editing?.reason}</SheetDescription></SheetHeader>{editing&&<form onSubmit={saveEdit} className="edit-form"><div className="edit-source">Source: {timeLabel(report.turns.find(t=>t.id===editing.turnId)?.arrival??null,report.date)} arrival · {timeLabel(report.turns.find(t=>t.id===editing.turnId)?.departure??null,report.date)} departure</div>{editing.warnings.map(w=><p key={w} className="edit-warning"><AlertTriangle size={15}/>{w}</p>)}<div className="edit-grid">{([['fin','FIN #','text'],['arrFlight','Arrival flight','text'],['from','Tow from','text'],['to','Tow to','text'],['pickup','Scheduled pickup','time'],['release','Aircraft release','time'],['gateOpen','Gate opens at','time'],['depFlight','Departure flight','text'],['depTime','Departure time','time'],['actualPickup','Actual pickup','time'],['actualDrop','Actual drop','time'],['tower','Tower','text']] as const).map(([key,label,type])=><label key={key}>{label}<Input type={type} readOnly={key==='depTime'} value={editing[key]} onChange={e=>setEditing({...editing,[key]:e.target.value,reviewed:false})}/></label>)}</div><label className="check-label"><Checkbox checked={editing.included} onCheckedChange={v=>setEditing({...editing,included:!!v})}/>Include on tow sheet</label>{editError&&<p role="alert" className="warning-text">{editError}</p>}<p className="muted">Saving confirms this route, timing and any warnings have been reviewed.</p><Button type="submit" className="button primary"><Check size={17}/>Save & mark reviewed</Button></form>}</SheetContent></Sheet>
 </>;
}
