'use client';
import { useEffect,useState } from 'react';
import { Plane,LayoutList,ScanLine,Moon,ListChecks,ArrowRight,Sun } from 'lucide-react';
import { Sidebar,SidebarHeader,SidebarContent,SidebarFooter,SidebarMenu,SidebarMenuItem,SidebarMenuButton,SidebarMenuBadge } from '@/components/ui/sidebar';
import { Sheet,SheetContent,SheetHeader,SheetTitle,SheetDescription } from '@/components/ui/sheet';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { type Move,type Report,timeLabel } from '@/lib/tows';
import { type ShutdownRow } from '@/lib/shutdown';
import { stationTimezone,towStatus,statusNames } from '@/lib/console';
export type OvernightSnapshot={rows:ShutdownRow[];date:string;dirty:boolean;generated:boolean};
export function ConsoleNav({tab,go,reviewCount,gateCount,overnightCount}:{tab:string;go:(tab:string)=>void;reviewCount:number;gateCount:number;overnightCount:number}){return <Sidebar collapsible="none" className="console-nav no-print"><SidebarHeader><div className="console-logo"><Plane size={21}/><span>Jazz<strong>Tow</strong></span></div><small>OPERATIONS CONSOLE</small></SidebarHeader><SidebarContent><div className="nav-caption">WORKSPACE</div><SidebarMenu>{[{id:'moves',label:'Tow Board',Icon:LayoutList,count:0},{id:'mismatch',label:'Gate Check',Icon:ScanLine,count:gateCount},{id:'shutdown',label:'Overnight',Icon:Moon,count:overnightCount},{id:'review',label:'Review',Icon:ListChecks,count:reviewCount}].map(({id,label,Icon,count})=><SidebarMenuItem key={id}><SidebarMenuButton aria-label={label} isActive={tab===id||id==='moves'&&['schedule','sheet'].includes(tab)} onClick={()=>go(id)} aria-current={tab===id?'page':undefined}><Icon/><span>{label}</span></SidebarMenuButton>{count>0&&<SidebarMenuBadge>{count}</SidebarMenuBadge>}</SidebarMenuItem>)}</SidebarMenu></SidebarContent><SidebarFooter><span className="console-session-dot"/>Session workspace<small>Export reports before leaving.</small></SidebarFooter></Sidebar>;}
export function StationHeader({station,date,uploadedAt}:{station:string;date:string;uploadedAt:number|null}){const [now,setNow]=useState<number|null>(null);useEffect(()=>{const first=setTimeout(()=>setNow(Date.now()),0);const timer=setInterval(()=>setNow(Date.now()),1000);return()=>{clearTimeout(first);clearInterval(timer);};},[]);const zone=stationTimezone(station);const time=(instant:number,tz:string)=>new Intl.DateTimeFormat('en-GB',{timeZone:tz,hour:'2-digit',minute:'2-digit',second:'2-digit',hourCycle:'h23'}).format(instant);return <header className="console-station no-print"><div className="station-identity"><strong>{station||'—'} <span>·</span> TOW CONTROL</strong><small>{date||'Operating date pending upload'}</small></div><div className="station-clocks"><div><small>{zone?'STATION LOCAL':'LOCAL ZONE UNKNOWN'}</small><strong>{now&&zone?time(now,zone):'—'}</strong></div><div><small>UTC</small><strong>{now?time(now,'UTC'):'—'}</strong></div></div><div className="upload-stamp"><span className={uploadedAt?'upload-led':''}/>{uploadedAt?`Schedule uploaded at ${new Intl.DateTimeFormat('en-GB',{timeZone:zone||'UTC',day:'2-digit',month:'short',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).format(uploadedAt)} ${zone?'local':'UTC'}`:'No schedule uploaded'}</div><ThemeToggle/></header>;}
function ThemeToggle(){const [dark,setDark]=useState(false);useEffect(()=>{const saved=localStorage.getItem('jazztow-theme');const enabled=saved?saved==='dark':window.matchMedia('(prefers-color-scheme: dark)').matches;setDark(enabled);document.documentElement.classList.toggle('dark',enabled);},[]);function toggle(){const enabled=!dark;setDark(enabled);document.documentElement.classList.toggle('dark',enabled);localStorage.setItem('jazztow-theme',enabled?'dark':'light');}return <Button type="button" variant="outline" size="icon" className="theme-toggle" onClick={toggle} aria-label={dark?'Use light mode':'Use dark mode'} title={dark?'Use light mode':'Use dark mode'}>{dark?<Sun/>:<Moon/>}</Button>;}
export function AircraftDrawer({fin,close,report,moves,overnight,edit}:{fin:string|null;close:()=>void;report:Report;moves:Move[];overnight:OvernightSnapshot;edit:(m:Move)=>void}){const turns=report.turns.filter(t=>t.fin===fin).sort((a,b)=>(a.arrival||0)-(b.arrival||0));const legs=moves.filter(m=>m.fin===fin).sort((a,b)=>a.pickup.localeCompare(b.pickup));const ron=overnight.rows.find(r=>r.fin===fin);return <Sheet open={!!fin} onOpenChange={open=>{if(!open)close();}}><SheetContent className="edit-sheet aircraft-drawer"><SheetHeader><SheetTitle>FIN <span className="mono">{fin}</span></SheetTitle><SheetDescription>{report.station} · {report.date} · Aircraft overview</SheetDescription></SheetHeader><div className="aircraft-content"><section><h3>OVERNIGHT LOCATION</h3>{ron?<><strong className="ron-location">{ron.ron}</strong><Badge variant="outline">{overnight.dirty?'Outdated inputs':ron.reviewed?'Reviewed':'Proposed'}</Badge><p>Night of {overnight.date}{ron.maintenance?' · Required at BSE':''}</p>{ron.depFlight&&<p>Next flight {ron.depFlight} · <span className="mono">{ron.std||'Time unavailable'}</span></p>}</>:<p>{overnight.generated?'Not listed in the overnight report.':'Prepare Overnight to assign a RON location.'}</p>}</section><section><h3>TOW LEGS <Badge variant="outline">{legs.length}</Badge></h3>{legs.map(m=><div className="aircraft-leg" key={m.id}><div><span className="mono">{m.pickup||'—'}</span><strong>{m.from||'?'} <ArrowRight size={14}/> {m.to||'?'}</strong><Badge variant="outline">{statusNames[towStatus(m,report.date)]}</Badge></div><p>Actual pickup {m.actualPickup||'—'} · Drop {m.actualDrop||'—'}</p><Button variant="ghost" onClick={()=>edit(m)}>Edit move</Button></div>)}{!legs.length&&<p>No tow legs planned for this aircraft.</p>}</section><section><h3>ARRIVALS & NEXT DEPARTURES</h3>{turns.map(t=><div className="aircraft-turn" key={t.id}><div><small>ARRIVAL · {t.origin}</small><strong>{t.arrFlight||'—'}</strong><span className="mono">{timeLabel(t.arrival,report.date)}</span><span>Gate {t.from||'—'}</span></div><ArrowRight size={17}/><div><small>NEXT DEPARTURE · {t.destination}</small><strong>{t.depFlight||'—'}</strong><span className="mono">{timeLabel(t.departure,report.date)}</span><span>Gate {t.to||'—'}</span></div></div>)}{!turns.length&&<p>No linked flight schedule for this FIN.</p>}</section></div></SheetContent></Sheet>;}
