'use client';
import { useState } from 'react';
import { AlertTriangle, ArrowRight, CheckCircle2, Route, ScanLine, Moon, Pencil } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { Input } from '@/components/ui/input';
import { Progress } from '@/components/ui/progress';
import { type Move,type Report,type Turn,timeLabel,moveErrors,gateArea,towLocation } from '@/lib/tows';
import { type OvernightSnapshot } from './operations-console';
export function ReviewWorkflow({report,moves,decisions,holding,issues,reviewCount,draft,gateConflicts,overnight,onFin,onHolding,onDecision,onRevisit,onEdit,onReview,onExclude,go}:{report:Report;moves:Move[];decisions:Record<string,string>;holding:Record<string,string>;issues:string[];reviewCount:number;draft:boolean;gateConflicts:number;overnight:OvernightSnapshot;onFin:(fin:string)=>void;onHolding:(id:string,value:string)=>void;onDecision:(turn:Turn,viaHolding:boolean)=>void;onRevisit:(turn:Turn)=>void;onEdit:(move:Move)=>void;onReview:(move:Move)=>void;onExclude:(move:Move)=>void;go:(page:string)=>void}){
 const [focused,setFocused]=useState<string|null>(null);
 const routes=report.turns.filter(t=>t.kind==='same-area'||t.kind==='long');
 const pending=routes.filter(t=>!decisions[t.id]);
 const active=pending.find(t=>t.id===focused)||pending[0];
 const selected=moves.filter(m=>m.included),awaiting=selected.filter(m=>!m.reviewed||moveErrors(m,report.date).length>0);
 const incomplete=moves.filter(m=>m.kind==='incomplete'&&!m.reviewed);
 const reviewed=selected.length-awaiting.length;
 return <div className="review-workspace"><div className="review-readiness"><div><strong className={draft?'text-warning':'text-success'}>{draft?`${reviewCount} tow review items require attention`:'Tow plan ready'}</strong><p>{draft?'Work through routing decisions and movement checks below.':'All required tow decisions have been reviewed.'}</p></div><div className="review-meter"><span>{reviewed} / {selected.length} included movements reviewed</span><Progress value={selected.length?reviewed/selected.length*100:0} aria-label="Tow review progress"/></div><Button variant="outline" onClick={()=>go('sheet')}>Preview sheet <ArrowRight size={15}/></Button></div>
 {report.warnings.map((warning,i)=><div className="message error" key={i}><AlertTriangle size={18}/><div><strong>Source correction required</strong><p>{warning} Correct the source and upload it again.</p></div></div>)}
 {issues.map(issue=><div className="message error" key={issue}><AlertTriangle size={18}/><span>{issue}</span><Button variant="outline" onClick={()=>go('moves')}>Inspect moves</Button></div>)}
 {active&&<section className="decision-workspace"><div className="section-heading"><h2>Routing decisions</h2><span className="text-warning">{pending.length} remaining</span></div><div className="decision-columns"><div className="decision-queue">{pending.map(t=><button key={t.id} onClick={()=>setFocused(t.id)} aria-pressed={active.id===t.id}><Route size={16}/><span><strong className="mono">FIN {t.fin||'unassigned'}</strong><small>{t.from} → {t.to} · {t.kind==='long'?'Long stay':'Same-area'}</small></span><ArrowRight size={14}/></button>)}</div><DecisionCard key={active.id} turn={active} date={report.date} holding={holding[active.id]||''} onHolding={value=>onHolding(active.id,value)} onConfirm={via=>onDecision(active,via)} onFin={()=>onFin(active.fin)}/></div></section>}
 {routes.some(t=>decisions[t.id])&&<details className="resolved-decisions"><summary><CheckCircle2 size={16}/> {routes.filter(t=>decisions[t.id]).length} resolved routing decisions</summary>{routes.filter(t=>decisions[t.id]).map(t=><div className="resolved-row" key={t.id}><CheckCircle2 size={16}/><Button variant="link" className="fin-link" onClick={()=>onFin(t.fin)}>FIN {t.fin}</Button><span>{decisions[t.id]==='stay'?`Stay at ${t.from}`:decisions[t.id]==='direct'?`${t.from} → ${t.to} · Direct tow`:`${t.from} → ${towLocation(holding[t.id]||'')} → ${t.to} · Via holding`}</span><Button variant="ghost" onClick={()=>onRevisit(t)}>Revisit</Button></div>)}</details>}
 {!!incomplete.length&&<section className="review-movement-section"><div className="section-heading"><h2>Incomplete turns</h2><span className="text-warning">{incomplete.length}</span></div>{incomplete.map(m=><article className="review-movement" key={m.id}><AlertTriangle size={17}/><div><Button variant="link" className="fin-link" onClick={()=>onFin(m.fin)}>FIN {m.fin||'unassigned'}</Button><p>{m.reason}</p>{m.warnings.map(w=><p className="text-warning" key={w}>{w}</p>)}</div><div className="actions"><Button variant="outline" onClick={()=>onEdit({...m,included:true})}>Complete move</Button><Button variant="ghost" onClick={()=>onExclude(m)}>Confirm no tow / exclude</Button></div></article>)}</section>}
 {!!awaiting.filter(m=>m.kind!=='incomplete').length&&<section className="review-movement-section"><div className="section-heading"><h2>Movement review</h2><span className="muted">Confirm each route and pickup</span></div>{awaiting.filter(m=>m.kind!=='incomplete').map(m=><article className="review-movement" key={m.id}><div className="review-movement-identity"><Button variant="link" className="fin-link" onClick={()=>onFin(m.fin)}>FIN {m.fin}</Button><span className="mono">{m.pickup||'Unset'} · {m.from||'?'} → {m.to||'?'}</span></div><div className="review-movement-description"><p>{m.reason}</p>{[...m.warnings,...moveErrors(m,report.date)].map((w,i)=><p className="text-warning" key={i}>{w}</p>)}</div><div className="actions"><Button variant="ghost" aria-label={`Edit review FIN ${m.fin} ${m.from} to ${m.to}`} onClick={()=>onEdit(m)}><Pencil size={14}/>Edit</Button><Button variant="outline" onClick={()=>onReview(m)}><CheckCircle2 size={15}/>Review move</Button></div></article>)}</section>}
 {!draft&&<div className="clear-state"><CheckCircle2 size={26}/><div><h2>Tow review complete</h2><p>The tow sheet is ready to preview, export or print.</p></div><Button className="button" onClick={()=>go('sheet')}>Open outputs <ArrowRight size={15}/></Button></div>}
 <div className="linked-reviews"><button onClick={()=>go('mismatch')}><ScanLine size={18}/><span><strong>Gate verification</strong><small>{gateConflicts?`${gateConflicts} assignment mismatches to compare`:'View source comparison and verification coverage'}</small></span><ArrowRight size={16}/></button><button onClick={()=>go('shutdown')}><Moon size={18}/><span><strong>Overnight review</strong><small>{overnight.dirty?'Inputs changed — regenerate overnight report':overnight.generated?`${overnight.rows.filter(r=>!r.reviewed).length} aircraft awaiting review`:'Overnight report not prepared'}</small></span><ArrowRight size={16}/></button></div><p className="review-scope-note">Tow, gate comparison and overnight reports retain separate review states. A ready tow sheet does not certify gate verification or overnight assignments.</p>
 {report.turns.some(t=>t.warnings.length)&&<details className="source-warnings"><summary>Aircraft source notes</summary>{report.turns.filter(t=>t.warnings.length).map(t=><div key={t.id}><Button variant="link" className="fin-link" onClick={()=>onFin(t.fin)}>FIN {t.fin||'unassigned'}</Button>{t.warnings.map(w=><p key={w}>{w}</p>)}</div>)}</details>}
 </div>;
}
function DecisionCard({turn,date,holding,onHolding,onConfirm,onFin}:{turn:Turn;date:string;holding:string;onHolding:(value:string)=>void;onConfirm:(holding:boolean)=>void;onFin:()=>void}){
 const [choice,setChoice]=useState('');
 return <article className="focused-decision"><div className="attention-title"><Badge variant="outline" className="execution-review">Needs decision</Badge><span className="section-kicker">{turn.kind==='long'?'LONG STAY':'ROUTING DECISION'}</span></div><div className="decision-aircraft-title"><Button variant="link" className="fin-link" onClick={onFin}>FIN {turn.fin||'unassigned'}</Button><span className="mono">{turn.from} → {turn.to}</span></div><div className="decision-flight-facts"><div><small>ARRIVAL</small><strong>{turn.arrFlight||'—'}</strong><span className="mono">{timeLabel(turn.arrival,date)} · {turn.from}</span></div><div><small>DEPARTURE</small><strong>{turn.depFlight||'—'}</strong><span className="mono">{timeLabel(turn.departure,date)} · {turn.to}</span></div><div><small>GROUND TIME</small><strong className="mono">{turn.duration===null?'—':`${Math.floor(turn.duration/60)}h ${turn.duration%60}m`}</strong><span>{turn.kind==='same-area'?`${gateArea(turn.from)} area`:'Same-gate stay'}</span></div></div><p>{turn.reason}</p><fieldset className="route-options"><legend>How should this aircraft be routed?</legend><label aria-label={turn.kind==='long'?'Keep at gate':'Direct tow'}><input type="radio" name={`route-${turn.id}`} value="direct" checked={choice==='direct'} onChange={()=>setChoice('direct')}/><span><strong>{turn.kind==='long'?'Keep at gate':'Direct tow'}</strong><small>{turn.kind==='long'?`Remain at ${turn.from}`:`${turn.from} → ${turn.to}`}</small></span></label><label aria-label="Via holding stand"><input type="radio" name={`route-${turn.id}`} value="holding" checked={choice==='holding'} onChange={()=>setChoice('holding')}/><span><strong>Via holding stand</strong><small>Arrival to holding, then return before departure</small></span></label>{choice==='holding'&&<label className="holding-field" htmlFor={`holding-${turn.id}`}>Holding stand<Input id={`holding-${turn.id}`} placeholder="e.g. S4B" value={holding} onChange={e=>onHolding(e.target.value)}/><small>Choose an actual stand different from both flight gates.</small></label>}</fieldset><div className="decision-confirm"><span>{choice==='holding'?'Both generated legs require movement review.':'Confirm after checking the operational assignment.'}</span><Button className="button primary" disabled={!choice||choice==='holding'&&!holding.trim()} onClick={()=>onConfirm(choice==='holding')}>Confirm decision <ArrowRight size={15}/></Button></div></article>;
}
