'use client';
import { useState,useEffect } from 'react';
import { Download, Printer, Moon, CheckCircle2, AlertTriangle, ArrowRight, Pencil } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import { Checkbox } from '@/components/ui/checkbox';
import { Card, CardHeader, CardTitle, CardDescription, CardContent } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { Alert, AlertTitle, AlertDescription } from '@/components/ui/alert';
import { Table, TableHeader, TableHead, TableRow, TableBody, TableCell } from '@/components/ui/table';
import { Sheet, SheetContent, SheetHeader, SheetTitle, SheetDescription } from '@/components/ui/sheet';
import { Select, SelectTrigger, SelectValue, SelectContent, SelectItem } from '@/components/ui/select';
import { type Report, towLocation } from '@/lib/tows';
import { buildShutdown, shutdownCSV, shutdownValues, shutdownHeaders, shutdownDraft, shutdownErrors, shutdownPlanErrors, type ShutdownRow } from '@/lib/shutdown';

function downloadText(text:string,name:string){const url=URL.createObjectURL(new Blob([text],{type:'text/csv;charset=utf-8;'}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
export default function ShutdownPlanner({report,onSnapshot,onFin}:{report:Report;onSnapshot?:(snapshot:import('./operations-console').OvernightSnapshot)=>void;onFin?:(fin:string)=>void}){
 const [night,setNight]=useState(report.date),[required,setRequired]=useState(''),[allowed,setAllowed]=useState('');
 const [rows,setRows]=useState<ShutdownRow[]>([]),[generated,setGenerated]=useState(false),[source,setSource]=useState(''),[reportNight,setReportNight]=useState(report.date),[error,setError]=useState('');
 const [editing,setEditing]=useState<ShutdownRow|null>(null),[editError,setEditError]=useState('');
 const dirty=generated&&source!==JSON.stringify([night,required,allowed]);const draft=dirty||shutdownDraft(rows);
 useEffect(()=>{onSnapshot?.({rows,date:reportNight,dirty,generated});},[rows,reportNight,dirty,generated,onSnapshot]);
 function generate(){try{const next=buildShutdown(report,night,required,allowed);setRows(next);setGenerated(true);setReportNight(night);setSource(JSON.stringify([night,required,allowed]));setError('');setEditing(null);}catch(e){setError((e as Error).message);}}
 function save(e:React.FormEvent){e.preventDefault();if(!editing)return;const normalized={...editing,ron:towLocation(editing.ron)};const errors=shutdownErrors(normalized);if(errors.length){setEditError(errors.join(' '));return;}setRows(rs=>rs.map(r=>r.fin===normalized.fin?{...normalized,reviewed:true}:r));setEditing(null);}
 function print(){document.body.dataset.printReport='shutdown';window.print();}
 return <div className="shutdown-workspace"><div className="shutdown-title no-print"><div><h2><Moon size={21}/> Overnight shutdown</h2><p>Prepare the maintenance and RON report for the selected night.</p></div><div className="actions"><Button variant="outline" className="button" disabled={!rows.length||dirty} onClick={()=>downloadText(shutdownCSV(rows,reportNight,report.station),`shutdown-${report.station}-${reportNight}${draft?'-DRAFT':''}.csv`)}><Download/>Export report</Button><Button className="button primary" disabled={!rows.length||dirty} onClick={print}><Printer/>Print report</Button></div></div>
 <Card className="maintenance-inputs no-print"><CardHeader><CardTitle>Nightly aircraft lists</CardTitle><CardDescription>Paste FIN numbers separated by spaces, commas, or newlines. Generating again replaces report edits.</CardDescription></CardHeader><CardContent><div className="maintenance-grid"><label>Shutdown night<Input type="date" value={night} onChange={e=>setNight(e.target.value)}/><small>Overnight into the following morning.</small></label><label>Required at BSE<Textarea placeholder="Enter FIN numbers" value={required} onChange={e=>setRequired(e.target.value)}/><small>These aircraft remain at HGR.</small></label><label>Can remain at gate<Textarea placeholder="Enter FIN numbers" value={allowed} onChange={e=>setAllowed(e.target.value)}/><small>Eligible aircraft are shown separately for an overnight gate request.</small></label></div><div className="maintenance-bottom"><p>Unlisted overnight FINs remain at HGR for review.</p><Button className="button primary" onClick={generate} disabled={!night}>{generated?'Regenerate report':'Generate shutdown report'}<ArrowRight/></Button></div></CardContent></Card>
 {error&&<Alert className="shutdown-alert no-print"><AlertTriangle/><AlertTitle>Check maintenance input</AlertTitle><AlertDescription>{error}</AlertDescription></Alert>}
 {shutdownPlanErrors(rows).map(issue=><Alert key={issue} className="shutdown-alert no-print"><AlertTriangle/><AlertTitle>Gate assignment conflict</AlertTitle><AlertDescription>{issue}</AlertDescription></Alert>)}
 {dirty&&<Alert className="shutdown-alert no-print"><AlertTriangle/><AlertTitle>Inputs have changed</AlertTitle><AlertDescription>Regenerate to apply the new maintenance list or night. Export and printing are paused to avoid using an outdated report.</AlertDescription></Alert>}
 {!generated&&<div className="empty-state shutdown-empty no-print"><Moon/><div><h3>No shutdown report yet</h3><p>Add the maintenance lists, then generate your report.</p></div></div>}
 {generated&&<><section className="shutdown-paper"><div className="shutdown-paper-title"><h2>SHUTDOWN REPORT</h2><span>{report.station} · Night of {reportNight}</span><Badge variant="outline">{draft?'DRAFT — REVIEW REQUIRED':'REVIEWED'}</Badge></div><Table className="shutdown-table"><TableHeader><TableRow>{shutdownHeaders.map(h=><TableHead key={h}>{h}</TableHead>)}<TableHead className="no-print">REVIEW</TableHead></TableRow></TableHeader><TableBody><ShutdownGroup onFin={onFin} title="REQUIRED BY MAINTENANCE" rows={rows.filter(r=>r.maintenance)} edit={r=>{setEditing({...r});setEditError('');}}/><ShutdownGroup onFin={onFin} title="MAY REMAIN AT GATE" rows={rows.filter(r=>!r.maintenance&&r.gateAllowed)} edit={r=>{setEditing({...r});setEditError('');}}/><ShutdownGroup onFin={onFin} title="OTHER OVERNIGHT AIRCRAFT" rows={rows.filter(r=>!r.maintenance&&!r.gateAllowed)} edit={r=>{setEditing({...r});setEditError('');}}/></TableBody></Table><p className="shutdown-print-footer">All times local. HGR = BSE hangar. US/TB defaults use the departure gate area and require review.</p></section></>}
 <Sheet open={!!editing} onOpenChange={open=>{if(!open)setEditing(null);}}><SheetContent className="edit-sheet"><SheetHeader><SheetTitle>Shutdown · FIN {editing?.fin}</SheetTitle><SheetDescription>Confirm the nightly location, next flight, and service requirements.</SheetDescription></SheetHeader>{editing&&<form className="edit-form" onSubmit={save}>{editing.warnings.map(w=><p key={w} className="edit-warning"><AlertTriangle size={15}/>{w}</p>)}<div className="edit-grid"><label>RON location<Input value={editing.ron} readOnly={editing.maintenance} onChange={e=>setEditing({...editing,ron:e.target.value})}/></label><label>Arrival flight<Input value={editing.arrFlight} onChange={e=>setEditing({...editing,arrFlight:e.target.value})}/></label><label>Departure flight<Input value={editing.depFlight} onChange={e=>setEditing({...editing,depFlight:e.target.value})}/></label><label>STD<Input type="time" value={editing.std} onChange={e=>setEditing({...editing,std:e.target.value})}/></label></div><label className="check-label"><Checkbox checked={editing.grooming} onCheckedChange={v=>setEditing({...editing,grooming:!!v})}/>Grooming required</label><label>Next planned flight is US / TB<Select value={editing.tb===null?'unknown':editing.tb?'yes':'no'} onValueChange={v=>setEditing({...editing,tb:v==='unknown'?null:v==='yes'})}><SelectTrigger aria-label="Next flight US / TB"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="unknown">Needs confirmation</SelectItem><SelectItem value="yes">Yes — mark X</SelectItem><SelectItem value="no">No — leave blank</SelectItem></SelectContent></Select></label><label>Comments<Textarea value={editing.comments} onChange={e=>setEditing({...editing,comments:e.target.value})}/></label>{editError&&<p role="alert" className="warning-text">{editError}</p>}<p className="muted">Save confirms that missing details and source warnings have been reviewed.</p><Button type="submit" className="button primary"><CheckCircle2/>Save & mark reviewed</Button></form>}</SheetContent></Sheet>
 </div>;
}
function ShutdownGroup({title,rows,edit,onFin}:{onFin?:(fin:string)=>void;title:string;rows:ShutdownRow[];edit:(r:ShutdownRow)=>void}){return <><TableRow className="shutdown-group"><TableCell colSpan={8}>{title}</TableCell><TableCell className="no-print"/></TableRow>{rows.map(r=><TableRow key={r.fin}>{shutdownValues(r).map((value,i)=><TableCell key={i} className={i===0?'fin':i===7?'shutdown-comments':''}>{i===0&&onFin?<Button variant="link" className="fin-link" onClick={()=>onFin(r.fin)}>{value}</Button>:value}</TableCell>)}<TableCell className="no-print"><Button variant="ghost" aria-label={`Review shutdown FIN ${r.fin}`} onClick={()=>edit(r)}>{r.reviewed?<CheckCircle2 size={15}/>:<Pencil size={15}/>} {r.reviewed?'Reviewed':'Review'}</Button></TableCell></TableRow>)}{!rows.length&&<TableRow><TableCell colSpan={8}>No aircraft in this section.</TableCell><TableCell className="no-print"/></TableRow>}</>}
