'use client';
import { ReportTimestamp } from '@/components/report-timestamp';
import { useState,useEffect,useMemo } from 'react';
import { Download, Printer, Moon, CheckCircle2, AlertTriangle, ArrowRight, Pencil, Plus, FileText } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import { Checkbox } from '@/components/ui/checkbox';
import { Badge } from '@/components/ui/badge';
import { Alert, AlertTitle, AlertDescription } from '@/components/ui/alert';
import { Table, TableHeader, TableHead, TableRow, TableBody, TableCell } from '@/components/ui/table';
import { Sheet, SheetContent, SheetHeader, SheetTitle, SheetDescription } from '@/components/ui/sheet';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription, DialogFooter } from '@/components/ui/dialog';
import { Select, SelectTrigger, SelectValue, SelectContent, SelectItem } from '@/components/ui/select';
import { type Report, towLocation } from '@/lib/tows';
import { buildShutdown, parseFins, updateGateRequest, shutdownCSV, shutdownValues, shutdownHeaders, shutdownDraft, shutdownErrors, shutdownPlanErrors, type ShutdownRow } from '@/lib/shutdown';

function downloadText(text:string,name:string){const url=URL.createObjectURL(new Blob([text],{type:'text/csv;charset=utf-8;'}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
export default function ShutdownPlanner({report,onSnapshot,onFin}:{report:Report;onSnapshot?:(snapshot:import('./operations-console').OvernightSnapshot)=>void;onFin?:(fin:string)=>void}){
 const [showReport,setShowReport]=useState(false),[confirmGenerate,setConfirmGenerate]=useState(false);
 const [night,setNight]=useState(report.date),[required,setRequired]=useState(''),[allowed,setAllowed]=useState('');
 const [rows,setRows]=useState<ShutdownRow[]>([]),[generated,setGenerated]=useState(false),[source,setSource]=useState(''),[reportNight,setReportNight]=useState(report.date),[error,setError]=useState('');
 const [editing,setEditing]=useState<ShutdownRow|null>(null),[editError,setEditError]=useState('');
 const detected=useMemo(()=>{try{return {rows:buildShutdown(report,night,required,allowed),error:''};}catch(e){return {rows:[],error:(e as Error).message};}},[report,night,required,allowed]);
 const displayRows=generated?rows:detected.rows;
 function classify(fin:string,target:'required'|'allowed'|'other'){try{const requiredFins=parseFins(required).filter(f=>f!==fin),allowedFins=parseFins(allowed).filter(f=>f!==fin);if(target==='required')requiredFins.push(fin);if(target==='allowed')allowedFins.push(fin);setRequired(requiredFins.join(' '));setAllowed(allowedFins.join(' '));setError('');}catch(e){setError((e as Error).message);}}
 const dirty=generated&&source!==JSON.stringify([night,required,allowed]);const draft=dirty||shutdownDraft(rows);
 useEffect(()=>{onSnapshot?.({rows,date:reportNight,dirty,generated});},[rows,reportNight,dirty,generated,onSnapshot]);
 function generate(){try{const next=buildShutdown(report,night,required,allowed);setRows(next);setGenerated(true);setReportNight(night);setSource(JSON.stringify([night,required,allowed]));setError('');setEditing(null);setConfirmGenerate(false);}catch(e){setError((e as Error).message);}}
 function save(e:React.SyntheticEvent<HTMLFormElement>){e.preventDefault();if(!editing)return;const normalized={...editing,ron:towLocation(editing.ron)};const errors=shutdownErrors(normalized);if(errors.length){setEditError(errors.join(' '));return;}setRows(rs=>rs.map(r=>r.fin===normalized.fin?{...normalized,reviewed:true}:r));setEditing(null);}
 function print(){document.body.dataset.printReport='shutdown';window.print();}
 return <div className="shutdown-workspace"><div className="shutdown-title no-print"><div><h2><Moon size={21}/> Night of {night}</h2><p>{displayRows.length} aircraft identified · Locations require operational review.</p></div><div className="actions"><Button variant="outline" className="button" disabled={!generated} onClick={()=>setShowReport(v=>!v)}><FileText/>{showReport?'Aircraft view':'Preview report'}</Button><Button variant="outline" className="button" disabled={!rows.length||dirty} onClick={()=>downloadText(shutdownCSV(rows,reportNight,report.station),`shutdown-${report.station}-${reportNight}${draft?'-DRAFT':''}.csv`)}><Download/>Export report</Button><Button className="button" disabled={!rows.length||dirty} onClick={print}><Printer/>Print report</Button></div></div>
 <div className="overnight-controls no-print"><label htmlFor="shutdown-night">Shutdown night<Input id="shutdown-night" type="date" value={night} onChange={e=>setNight(e.target.value)}/></label><p>Includes overnight arrivals before 08:00 the following morning.</p><Button className="button primary" onClick={()=>generated?setConfirmGenerate(true):generate()} disabled={!night||!!detected.error}>{generated?'Regenerate report':'Generate overnight report'}<ArrowRight size={15}/></Button></div>
 <details className="bulk-fin-input no-print"><summary><Plus size={15}/> Add FIN manually / paste aircraft lists</summary><div className="maintenance-grid"><label htmlFor="required-fins">Required at BSE / HGR<Textarea id="required-fins" placeholder="Paste FIN numbers" value={required} onChange={e=>setRequired(e.target.value)}/><small>Maintenance-required aircraft remain at HGR.</small></label><label htmlFor="allowed-fins">Can remain at gate<Textarea id="allowed-fins" placeholder="Paste FIN numbers" value={allowed} onChange={e=>setAllowed(e.target.value)}/><small>Permission does not confirm a gate assignment.</small></label></div><p>Separate FINs with spaces, commas or newlines. Aircraft absent from the schedule remain visible for manual review.</p></details>
 {detected.error&&<p role="alert" className="warning-text no-print">{detected.error}</p>}
 <div className="overnight-groups no-print">{([{title:'Required at BSE / HGR',type:'required',subtitle:'Maintenance list · HGR required',items:displayRows.filter(r=>r.maintenance)},{title:'Can remain at gate',type:'allowed',subtitle:'Gate permission · assignment must be reviewed',items:displayRows.filter(r=>!r.maintenance&&r.gateAllowed)},{title:'Needs classification',type:'other',subtitle:'Not on either list · HGR until confirmed',items:displayRows.filter(r=>!r.maintenance&&!r.gateAllowed)}] as const).map(group=><section key={group.type}><div className="section-heading"><h2>{group.title}</h2><span className="table-count">{group.items.length}</span></div><p>{group.subtitle}</p><div className="overnight-aircraft-list">{group.items.map(r=><article className="overnight-aircraft" key={r.fin}><div><Button variant="link" className="fin-link" onClick={()=>onFin?.(r.fin)}>FIN {r.fin}</Button><Badge variant="outline" className={generated&&r.reviewed?'execution-completed':'execution-review'}>{generated&&r.reviewed?'Reviewed':generated?'Needs review':'Proposed'}</Badge></div><p><span className="mono">{r.ron}</span> · {r.depFlight||'Next flight unknown'} · <span className="mono">{r.std||'Time unknown'}</span></p>{r.requestStatus==='pending'&&<small className="text-warning">Gate {r.requestedGate||'TBC'} request pending</small>}<div className="overnight-aircraft-actions"><label className="sr-only" htmlFor={`classification-${r.fin}`}>Classification for FIN {r.fin}</label><select id={`classification-${r.fin}`} value={group.type} onChange={e=>classify(r.fin,e.target.value as 'required'|'allowed'|'other')} disabled={dirty}><option value="required">Required at BSE / HGR</option><option value="allowed">Can remain at gate</option><option value="other">Needs classification</option></select>{generated&&<Button variant="ghost" disabled={dirty} aria-label={`Review overnight FIN ${r.fin}`} onClick={()=>{setEditing({...r});setEditError('');}}><Pencil size={13}/>Review</Button>}</div></article>)}{!group.items.length&&<div className="overnight-group-empty">No aircraft in this group.</div>}</div></section>)}</div>
 {generated&&<div className="overnight-readiness no-print"><span className={draft?'text-warning':'text-success'}>{dirty?'Inputs changed — regenerate before reviewing or exporting.':draft?`${rows.filter(r=>!r.reviewed||shutdownErrors(r).length||r.requestStatus==='pending').length} aircraft need review${shutdownPlanErrors(rows).length?' · Gate conflicts remain':''}.`:'Overnight report reviewed and ready for output.'}</span><Button variant="ghost" onClick={()=>setShowReport(v=>!v)}>{showReport?'Hide report preview':'Preview report'}<ArrowRight size={14}/></Button></div>}

 {error&&<Alert className="shutdown-alert no-print"><AlertTriangle/><AlertTitle>Check maintenance input</AlertTitle><AlertDescription>{error}</AlertDescription></Alert>}
 {shutdownPlanErrors(rows).map(issue=><Alert key={issue} className="shutdown-alert no-print"><AlertTriangle/><AlertTitle>Gate assignment conflict</AlertTitle><AlertDescription>{issue}</AlertDescription></Alert>)}
 {dirty&&<Alert className="shutdown-alert no-print"><AlertTriangle/><AlertTitle>Inputs have changed</AlertTitle><AlertDescription>Regenerate to apply the new maintenance list or night. Export and printing are paused to avoid using an outdated report.</AlertDescription></Alert>}
 {!generated&&<div className="inline-note no-print"><Moon size={16}/>{displayRows.length?'Classify the detected aircraft or paste the nightly lists, then generate the report.':'No overnight aircraft detected. Add FINs manually if needed.'}</div>}
 {generated&&<><section className={`shutdown-paper ${showReport?'':'report-collapsed'}`}><div className="shutdown-paper-title"><h2>SHUTDOWN REPORT</h2><span>{report.station} · Night of {reportNight}</span><Badge variant="outline">{draft?'DRAFT — REVIEW REQUIRED':'REVIEWED'}</Badge></div><Table className="shutdown-table"><TableHeader><TableRow>{shutdownHeaders.map(h=><TableHead key={h}>{h}</TableHead>)}<TableHead className="no-print">REVIEW</TableHead></TableRow></TableHeader><TableBody><ShutdownGroup onFin={onFin} title="REQUIRED BY MAINTENANCE" rows={rows.filter(r=>r.maintenance)} edit={r=>{setEditing({...r});setEditError('');}}/><ShutdownGroup onFin={onFin} title="MAY REMAIN AT GATE" rows={rows.filter(r=>!r.maintenance&&r.gateAllowed)} edit={r=>{setEditing({...r});setEditError('');}}/><ShutdownGroup onFin={onFin} title="OTHER OVERNIGHT AIRCRAFT" rows={rows.filter(r=>!r.maintenance&&!r.gateAllowed)} edit={r=>{setEditing({...r});setEditError('');}}/></TableBody></Table><div className="shutdown-generated"><ReportTimestamp station={report.station}/></div><p className="shutdown-print-footer">All times local. HGR = BSE hangar. US/TB defaults use the departure gate area and require review.</p></section></>}
 <Sheet open={!!editing} onOpenChange={open=>{if(!open)setEditing(null);}}><SheetContent className="edit-sheet"><SheetHeader><SheetTitle>Shutdown · FIN {editing?.fin}</SheetTitle><SheetDescription>Confirm the nightly location, next flight, and service requirements.</SheetDescription></SheetHeader>{editing&&<form className="edit-form" onSubmit={save}>{editing.warnings.map(w=><p key={w} className="edit-warning"><AlertTriangle size={15}/>{w}</p>)}{editing.eligible&&<section className="gate-request-editor"><h3>Overnight gate request</h3><p className="muted">Record the confirmed operational decision. No request is sent by this app.</p><label htmlFor="requested-gate">Requested gate<Input id="requested-gate" value={editing.requestedGate} onChange={e=>setEditing({...editing,requestedGate:e.target.value})}/></label><label htmlFor="gate-request-status">Request status<select id="gate-request-status" value={editing.requestStatus} onChange={e=>{try{setEditing(updateGateRequest(editing,e.target.value as ShutdownRow['requestStatus'],editing.requestedGate));setEditError('');}catch(error){setEditError((error as Error).message);}}}><option value="pending">Awaiting approval</option><option value="approved">Approval confirmed</option><option value="declined">Declined — HGR</option><option value="none">No active request — HGR</option></select></label></section>}<div className="edit-grid"><label>RON location<Input value={editing.ron} readOnly={editing.maintenance} onChange={e=>setEditing({...editing,ron:e.target.value})}/></label><label>Arrival flight<Input value={editing.arrFlight} onChange={e=>setEditing({...editing,arrFlight:e.target.value})}/></label><label>Departure flight<Input value={editing.depFlight} onChange={e=>setEditing({...editing,depFlight:e.target.value})}/></label><label>STD<Input type="time" value={editing.std} onChange={e=>setEditing({...editing,std:e.target.value})}/></label></div><label className="check-label"><Checkbox checked={editing.grooming} onCheckedChange={v=>setEditing({...editing,grooming:!!v})}/>Grooming required</label><label>Next planned flight is US / TB<Select value={editing.tb===null?'unknown':editing.tb?'yes':'no'} onValueChange={v=>setEditing({...editing,tb:v==='unknown'?null:v==='yes'})}><SelectTrigger aria-label="Next flight US / TB"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="unknown">Needs confirmation</SelectItem><SelectItem value="yes">Yes — mark X</SelectItem><SelectItem value="no">No — leave blank</SelectItem></SelectContent></Select></label><label>Comments<Textarea value={editing.comments} onChange={e=>setEditing({...editing,comments:e.target.value})}/></label>{editError&&<p role="alert" className="warning-text">{editError}</p>}<p className="muted">Save confirms that missing details and source warnings have been reviewed.</p><Button type="submit" className="button primary"><CheckCircle2/>Save & mark reviewed</Button></form>}</SheetContent></Sheet>
 <Dialog open={confirmGenerate} onOpenChange={setConfirmGenerate}><DialogContent><DialogHeader><DialogTitle>Regenerate overnight report?</DialogTitle><DialogDescription>This applies the current aircraft lists and night, replacing edited assignments and review decisions in the current overnight report.</DialogDescription></DialogHeader><DialogFooter><Button variant="outline" onClick={()=>setConfirmGenerate(false)}>Keep current report</Button><Button className="button primary" onClick={generate}>Regenerate report</Button></DialogFooter></DialogContent></Dialog>
 </div>;
}
function ShutdownGroup({title,rows,edit,onFin}:{onFin?:(fin:string)=>void;title:string;rows:ShutdownRow[];edit:(r:ShutdownRow)=>void}){return <><TableRow className="shutdown-group"><TableCell colSpan={8}>{title}</TableCell><TableCell className="no-print"/></TableRow>{rows.map(r=><TableRow key={r.fin}>{shutdownValues(r).map((value,i)=><TableCell key={i} className={i===0?'fin':i===7?'shutdown-comments':''}>{i===0&&onFin?<Button variant="link" className="fin-link" onClick={()=>onFin(r.fin)}>{value}</Button>:value}</TableCell>)}<TableCell className="no-print"><Button variant="ghost" aria-label={`Review shutdown FIN ${r.fin}`} onClick={()=>edit(r)}>{r.reviewed?<CheckCircle2 size={15}/>:<Pencil size={15}/>} {r.reviewed?'Reviewed':'Review'}</Button></TableCell></TableRow>)}{!rows.length&&<TableRow><TableCell colSpan={8}>No aircraft in this section.</TableCell><TableCell className="no-print"/></TableRow>}</>}
